### ISSUE TITLE
Use FlashCat's personal access token for pushing docs

### ISSUE THREAD

**Issue by apasel422** [contain-rs/compare#12]
Instead of using my (or @Gankro's) personal access token as the value of the `GH_TOKEN` environment variable on Travis CI, we should create one from @FlashCat's GitHub account. This will limit the consequences of the token being compromised.

Whoever has FlashCat's GitHub credentials should do the following:
1. Log in to GitHub as FlashCat, and [create a new personal access token](https://github.com/settings/tokens/new) with only the `public_repo` permission.
2. Copy the token to the clipboard.
3. Delete the current `GH_TOKEN` environment variable by visiting https://travis-ci.org/contain-rs/compare/settings/env_vars.
4. Re-create the `GH_TOKEN` environment variable with the token that was copied, ensuring that the "Display value in build logs" settings is "OFF" (which it is by default).
5. Repeat for each of the other `contain-rs` repos.

**Comment by Gankra** [comment]
Done

**Comment by apasel422** [comment]
Just making sure: This has been done for all the repos? (So I can delete the tokens I created with my account.)

**Comment by Gankra** [comment]
Everything but admin and rust-highfive

**Comment by apasel422** [comment]
Awesome, thanks!
